CXX =mpiCC 

PROG=sinep
TESTOBJ = sinep.o get_dat.o lagrange.o sinepclc.o \
	  sinepvar.o snp_fltr.o param.o

LIBS=-lm
INC= -I/usr/local/mpi/include/ -I/usr/local/include -I/usr/include/g++-2
CLOADFLAGS =-O 
CCFLAGS=-O

.SUFFIXES:

.SUFFIXES: .cpp .o

all:exe 


exe: $(TESTOBJ)
	$(CXX)  $(CLOADFLAGS) -o $(PROG) $(TESTOBJ) $(LIBS) 

clean :
	rm -f *.o $(PROG)

.f.o : ; $(F77) -c $(F77FLAGS) $*.f

.cpp.o : ; $(CXX) -c $(INC) $(CCFLAGS)  $*.cpp
